name: TownyPacts
version: '1.0'
main: org.breakthebot.townyPacts.TownyPacts
api-version: '1.21'
authors: [ Jinzo, Veyronity ]
permissions:
  towny.command.nation.pact.list:
    description: Allow a player to list pacts of a nation
    default: true
  towny.command.nation.pact.info:
    description: Allow a player to view a pact's information
    default: true
  towny.command.nation.pact.send:
    description: Allow a player to send a pact request
    default: op
  towny.command.nation.pact.accept:
    description: Allow a player to accept a pact
    default: op
  towny.command.nation.pact.break:
    description: Allow a player to force-break a pact
    default: op
  towny.command.nation.pact.deny:
    description: Allow a player to deny a pact
    default: op
  towny.command.nation.pact.revoke:
    description: Allow a player to revoke a sent pact
    default: op
  towny.command.nation.pact.manage:
    description: Allow a player to send, accept, break, and deny pacts
    default: op